services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mikolaj
      POSTGRES_PASSWORD: investmentPassword77
      POSTGRES_DB: InvestmentDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: